#!/usr/bin/env tsx
/**
 * plan.ts <vault-root>
 *
 * Scan an Obsidian vault that has the AI Attachmate plugin configured.
 * Emit a JSON plan to stdout classifying every attachment as:
 *   newFiles   — no transcript yet
 *   staleFiles — transcript exists but source mtime >= transcript mtime
 *   orphans    — transcript exists but source is gone
 *   upToDate   — count of transcripts that are current (no action needed)
 *
 * For staleFiles, the userZone (content above AUTOGENERATED_MARKER) is
 * pre-extracted so write-transcript.ts can preserve it without a re-read.
 */

import { readFileSync, statSync, readdirSync, existsSync } from 'fs'
import { join, relative } from 'path'
import micromatch from 'micromatch'
import {
	AUTOGENERATED_MARKER,
	DEFAULT_FILE_FILTER,
	DEFAULT_PROMPT,
	DEFAULT_TEMPLATE,
	DEFAULT_TRANSCRIPTS_FOLDER,
} from './_synced/constants'

type Settings = {
	transcriptsFolder: string
	fileFilter: string
	prompt: string
	template: string
}

type FileEntry = { path: string; mtime: number }

const SOURCE_EXTS = ['.canvas', '.pdf', '.png', '.jpg', '.jpeg'] as const
const TARGET_FOR: Record<string, string> = {
	'.canvas': '.canvas.md',
	'.pdf': '.pdf.md',
	'.png': '.png.md',
	'.jpg': '.jpg.md',
	'.jpeg': '.jpeg.md',
}

function loadSettings(vault: string): Settings {
	const dataPath = join(vault, '.obsidian/plugins/ai-attachmate/data.json')
	const defaults: Settings = {
		transcriptsFolder: DEFAULT_TRANSCRIPTS_FOLDER,
		fileFilter: DEFAULT_FILE_FILTER,
		prompt: DEFAULT_PROMPT,
		template: DEFAULT_TEMPLATE,
	}
	if (!existsSync(dataPath)) return defaults
	const raw = JSON.parse(readFileSync(dataPath, 'utf8')) as Partial<Settings>
	return { ...defaults, ...raw }
}

function walkVault(vault: string): FileEntry[] {
	const out: FileEntry[] = []
	const skip = new Set(['.obsidian', '.trash', '.git', 'node_modules'])
	const walk = (dir: string): void => {
		for (const entry of readdirSync(dir, { withFileTypes: true })) {
			if (skip.has(entry.name)) continue
			const full = join(dir, entry.name)
			if (entry.isDirectory()) {
				walk(full)
			} else if (entry.isFile()) {
				const stat = statSync(full)
				out.push({ path: relative(vault, full).split('\\').join('/'), mtime: stat.mtimeMs })
			}
		}
	}
	walk(vault)
	return out
}

function isRelativeTranscriptsFolder(tf: string): boolean {
	return tf.startsWith('./') || tf.startsWith('../')
}

function resolveRelativeDir(sourceDir: string, tf: string): string {
	const parts = sourceDir ? sourceDir.split('/') : []
	let remaining = tf
	while (remaining.startsWith('../')) {
		if (parts.length > 0) parts.pop()
		remaining = remaining.slice(3)
	}
	if (remaining.startsWith('./')) remaining = remaining.slice(2)
	if (remaining) parts.push(remaining)
	return parts.join('/')
}

function getTargetPath(sourcePath: string, transcriptsFolder: string): string {
	const sourceName = sourcePath.split('/').at(-1) ?? sourcePath
	const sourceDir = sourcePath.includes('/') ? sourcePath.split('/').slice(0, -1).join('/') : ''
	const ext = SOURCE_EXTS.find((e) => sourceName.endsWith(e))
	if (!ext) throw new Error(`Unrecognized extension: ${sourcePath}`)
	const outName = sourceName.slice(0, -ext.length) + TARGET_FOR[ext]

	if (isRelativeTranscriptsFolder(transcriptsFolder)) {
		const dir = resolveRelativeDir(sourceDir, transcriptsFolder)
		return dir ? `${dir}/${outName}` : outName
	}
	const normalized = transcriptsFolder.replace(/^\/+/, '').replace(/\/+$/, '')
	return normalized ? `${normalized}/${outName}` : outName
}

function getSourceNameFromTarget(targetName: string): string | null {
	for (const ext of SOURCE_EXTS) {
		const targetExt = TARGET_FOR[ext]
		if (targetName.endsWith(targetExt)) {
			return targetName.slice(0, -targetExt.length) + ext
		}
	}
	return null
}

function extractUserZone(transcriptContent: string): string {
	if (!transcriptContent.includes(AUTOGENERATED_MARKER)) return ''
	const [userZone] = transcriptContent.split(AUTOGENERATED_MARKER)
	return userZone
}

export type Plan = {
	vault: string
	prompt: string
	template: string
	newFiles: { source: string; target: string }[]
	staleFiles: { source: string; target: string; userZone: string }[]
	orphans: string[]
	upToDate: number
}

export function runPlan(vault: string): Plan {
	const settings = loadSettings(vault)
	const allFiles = walkVault(vault)
	const filePathToEntry = new Map(allFiles.map((f) => [f.path, f]))

	const filteredPaths = new Set(
		micromatch(
			allFiles.map((f) => f.path),
			settings.fileFilter,
		),
	)
	const sourceFiles = allFiles.filter(
		(f) =>
			SOURCE_EXTS.some((ext) => f.path.endsWith(ext)) &&
			filteredPaths.has(f.path) &&
			!f.path.endsWith('.canvas.md'), // not a source — defensive
	)

	const newFiles: { source: string; target: string }[] = []
	const staleFiles: { source: string; target: string; userZone: string }[] = []
	const knownTargets = new Set<string>()
	let upToDate = 0

	for (const source of sourceFiles) {
		const target = getTargetPath(source.path, settings.transcriptsFolder)
		knownTargets.add(target)
		const targetEntry = filePathToEntry.get(target)
		if (!targetEntry) {
			newFiles.push({ source: source.path, target })
			continue
		}
		if (source.mtime >= targetEntry.mtime) {
			const content = readFileSync(join(vault, target), 'utf8')
			staleFiles.push({ source: source.path, target, userZone: extractUserZone(content) })
		} else {
			upToDate++
		}
	}

	// Orphans: transcripts that look auto-generated whose source is gone.
	// Only consider files that (a) match a known target extension, (b) live in a
	// directory we'd produce output into, (c) contain the AUTOGENERATED_MARKER.
	const sourceNamesSet = new Set(sourceFiles.map((f) => f.path.split('/').at(-1) ?? f.path))
	const targetExtensions = Object.values(TARGET_FOR)
	const orphans: string[] = []
	for (const f of allFiles) {
		if (knownTargets.has(f.path)) continue
		const name = f.path.split('/').at(-1) ?? f.path
		if (!targetExtensions.some((te) => name.endsWith(te))) continue
		const sourceName = getSourceNameFromTarget(name)
		if (!sourceName) continue
		if (sourceNamesSet.has(sourceName)) continue
		// Verify it's auto-generated before considering it an orphan
		const content = readFileSync(join(vault, f.path), 'utf8')
		if (!content.includes(AUTOGENERATED_MARKER)) continue
		orphans.push(f.path)
	}

	return {
		vault,
		prompt: settings.prompt,
		template: settings.template,
		newFiles,
		staleFiles,
		orphans,
		upToDate,
	}
}

function main(): void {
	const vault = process.argv[2]
	if (!vault) {
		console.error('Usage: plan.ts <vault-root>')
		process.exit(2)
	}
	if (!existsSync(join(vault, '.obsidian'))) {
		console.error(`Not an Obsidian vault (no .obsidian/): ${vault}`)
		process.exit(2)
	}
	const plan = runPlan(vault)
	process.stdout.write(JSON.stringify(plan, null, 2) + '\n')
}

const isMain =
	import.meta.url === `file://${process.argv[1]}` ||
	process.argv[1]?.endsWith('plan.ts') ||
	process.argv[1]?.endsWith('plan.js')
if (isMain) main()
