#!/usr/bin/env tsx
/**
 * write-transcript.ts --vault <v> --source <s> --target <t> [--user-zone <z>] [--canvas]
 *
 * Reads the AI-produced transcript body from stdin and writes the final
 * transcript file. Applies the configured template (loaded from the vault's
 * data.json) and preserves the userZone (content above AUTOGENERATED_MARKER)
 * when it is non-empty.
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs'
import { join, dirname } from 'path'
import { applyTemplate } from './_synced/applyTemplate'
import { AUTOGENERATED_MARKER, DEFAULT_TEMPLATE } from './_synced/constants'

function arg(flag: string): string | undefined {
	const i = process.argv.indexOf(flag)
	return i === -1 ? undefined : process.argv[i + 1]
}
const hasFlag = (flag: string): boolean => process.argv.includes(flag)

function loadTemplate(vault: string): string {
	const dataPath = join(vault, '.obsidian/plugins/ai-attachmate/data.json')
	if (!existsSync(dataPath)) return DEFAULT_TEMPLATE
	const raw = JSON.parse(readFileSync(dataPath, 'utf8')) as { template?: string }
	return raw.template ?? DEFAULT_TEMPLATE
}

function readStdin(): string {
	return readFileSync(0, 'utf8')
}

function main(): void {
	const vault = arg('--vault')
	const source = arg('--source')
	const target = arg('--target')
	const userZone = arg('--user-zone') ?? ''
	const isCanvas = hasFlag('--canvas') || (source?.endsWith('.canvas') ?? false)

	if (!vault || !source || !target) {
		console.error('Usage: write-transcript.ts --vault <v> --source <s> --target <t> [--user-zone <z>] [--canvas]')
		process.exit(2)
	}

	const body = readStdin()
	const template = loadTemplate(vault)
	const filename = source.split('/').at(-1) ?? source

	const newContent = applyTemplate(
		template,
		{ filename, path: source, targetPath: target },
		body,
		{ canvas: isCanvas },
	)

	let finalContent = newContent
	if (userZone) {
		const [, autoZone] = newContent.split(AUTOGENERATED_MARKER)
		finalContent = `${userZone}${AUTOGENERATED_MARKER}${autoZone}`
	}

	const targetAbs = join(vault, target)
	mkdirSync(dirname(targetAbs), { recursive: true })
	writeFileSync(targetAbs, finalContent)
	console.log(`wrote: ${target}`)
}

main()
