import { AUTOGENERATED_MARKER } from '../utils/constants'
import { FileAdapter } from './FileAdapter'
import { File, FileDao } from './FileDao'

export class FileDaoImpl implements FileDao {
	constructor(private fileAdapter: FileAdapter) {}

	async readFile(path: string): Promise<string | undefined> {
		try {
			return await this.fileAdapter.read(path)
		} catch {
			return undefined
		}
	}

	async deleteFile(path: string): Promise<void> {
		// Verify file contains one of the valid description markers before deletion
		const content = await this.readFile(path)
		if (content && !content.includes(AUTOGENERATED_MARKER)) {
			throw new Error(
				`Cannot delete file at ${path} - it does not appear to be a generated transcript`,
			)
		}
		await this.fileAdapter.delete(path)
	}

	async createOrUpdateFile(path: string, content: string): Promise<void> {
		try {
			// First try to modify existing file
			await this.fileAdapter.modify(path, content)
		} catch {
			// If modify fails, try to create new file
			try {
				await this.fileAdapter.create(path, content)
			} catch (createError) {
				console.error(`Error in createOrUpdateFile for path ${path}:`, createError)
				throw createError
			}
		}
	}

	getFiles(): File[] {
		const files = this.fileAdapter.getFiles()
		return files.map(
			(file) =>
				new File(
					file.path,
					file.name,
					file.modifiedTime,
					file.sizeInBytes,
					() => this.fileAdapter.read(file.path),
					() => this.fileAdapter.readBinary(file.path),
				),
		)
	}

	createFolder(path: string): Promise<void> {
		return this.fileAdapter.createFolder(path)
	}
}
