import { AUTOGENERATED_MARKER } from './constants'

function relativeEncodedPath(sourcePath: string, targetPath: string): string {
	const targetDir = targetPath.includes('/') ? targetPath.split('/').slice(0, -1).join('/') : ''
	const fromParts = targetDir ? targetDir.split('/') : []
	const toParts = sourcePath.split('/')

	let i = 0
	while (i < fromParts.length && i < toParts.length && fromParts[i] === toParts[i]) {
		i++
	}

	const ups = fromParts.length - i
	const downs = toParts.slice(i)
	const parts = [...Array(ups).fill('..'), ...downs]
	const rel = parts.join('/')
	const prefixed = rel.startsWith('..') ? rel : `./${rel}`
	return prefixed.replace(/ /g, '%20')
}

export function applyTemplate(
	template: string,
	vars: { filename: string; path: string; targetPath: string },
	transcript: string,
	options?: { canvas?: boolean },
): string {
	let header = template
		.replace(/\{\{filename\}\}/g, vars.filename)
		.replace(/\{\{path\}\}/g, relativeEncodedPath(vars.path, vars.targetPath))

	if (options?.canvas) {
		header = header.replace(/#height=\d+/g, '')
	}

	return `${header}\n\n${AUTOGENERATED_MARKER}\n# Transcript\n\n${transcript}`
}
