import { AUTOGENERATED_MARKER } from './constants'

export function applyTemplate(
	template: string,
	vars: { filename: string; path: string },
	transcript: string,
	options?: { canvas?: boolean },
): string {
	let header = template.replace(/\{\{filename\}\}/g, vars.filename).replace(/\{\{path\}\}/g, vars.path)

	if (options?.canvas) {
		header = header.replace(/#height=\d+/g, '')
	}

	return `${header}\n\n${AUTOGENERATED_MARKER}\n# Transcript\n\n${transcript}`
}
