export const WEBPAGE_TEMPLATE = '![Web Page]({element})'

export const CARD_TEMPLATE = '{element}\n___'

export const NOTE_TEMPLATE = '![[{element}]]'

export const MEDIA_TEMPLATE = '![[{element}|500]]'

export const AUTOGENERATED_MARKER = '<!--auto-generate-content-below-->'

export const DEFAULT_FILE_FILTER = '**/*.{canvas,pdf,png,jpg,jpeg}'

export const DEFAULT_INDEX_FOLDER = './'

export const DEFAULT_PROMPT = `Transcribe the complete content of this document or image into well-structured markdown.
- Use ## for top-level sections and ### for subsections, using the exact section titles from the source (e.g. "## 1. Introduction", "## Conclusion")
- Never use bold text (**like this**) as a substitute for headings
- Preserve all body text faithfully and in full
- Render tables using markdown table syntax, always with a blank line before and after the table
- For figures and images, write a brief italicised description on its own line`
