export const INDEX_FILE_DESCRIPTION =
	"This index file enables Obsidian and its plugins to manage canvas files effectively. It ensures alias files for canvases appear in graphs and allows plugins compatible only with MD files to access these files.";

export const INDEX_FILE_TEMPLATE =
	"[[{element}]]\n\n" + INDEX_FILE_DESCRIPTION;

export const WEBPAGE_TEMPLATE = "![Web Page]({element})";

export const CARD_TEMPLATE = "{element}\n___";

export const NOTE_TEMPLATE = "![[{element}]]";

export const MEDIA_TEMPLATE = "![[{element}|500]]";

export const IMAGE_FILE_DESCRIPTION =
	"This index file enables Obsidian and its plugins to manage image files effectively. It ensures image files appear in graphs and allows plugins compatible only with MD files to access these files.";

export const PDF_FILE_DESCRIPTION =
	"This index file enables Obsidian and its plugins to manage PDF files effectively. It ensures PDF files appear in graphs and allows plugins compatible only with MD files to access these files.";

export const AUTOGENERATED_MARKER = "<!--auto-generate-content-below-->";
