import { describe, expect, it } from 'vitest'
import { applyTemplate } from '../../src/utils/applyTemplate'
import { AUTOGENERATED_MARKER } from '../../src/utils/constants'

describe('applyTemplate', () => {
	it('replaces {{filename}} with the provided filename', () => {
		const result = applyTemplate(
			'File: {{filename}}',
			{ filename: 'test.pdf', path: 'docs/test.pdf', targetPath: 'transcripts/test.pdf.md' },
			'transcript',
		)
		expect(result).toContain('File: test.pdf')
		expect(result).not.toContain('{{filename}}')
	})

	it('{{path}} is relative from target dir to source, spaces encoded', () => {
		const result = applyTemplate(
			'[name]({{path}})\n![]({{path}}#height=500)',
			{ filename: 'some doc.pdf', path: 'attachments/some doc.pdf', targetPath: 'transcripts/some doc.pdf.md' },
			'transcript',
		)
		expect(result).toContain('[name](../attachments/some%20doc.pdf)')
		expect(result).toContain('![](../attachments/some%20doc.pdf#height=500)')
		expect(result).not.toContain('{{path}}')
	})

	it('{{path}} uses ./ prefix when source and target are in the same folder', () => {
		const result = applyTemplate(
			'![]({{path}}#height=500)',
			{ filename: 'some doc.pdf', path: 'attachments/some doc.pdf', targetPath: 'attachments/some doc.pdf.md' },
			'transcript',
		)
		expect(result).toContain('![](./some%20doc.pdf#height=500)')
	})

	it('{{path}} handles source at vault root', () => {
		const result = applyTemplate(
			'![]({{path}})',
			{ filename: 'some doc.pdf', path: 'some doc.pdf', targetPath: 'transcripts/some doc.pdf.md' },
			'transcript',
		)
		expect(result).toContain('![](../some%20doc.pdf)')
	})

	it('{{path}} handles subfolder with spaces in path', () => {
		const result = applyTemplate(
			'[name]({{path}})',
			{ filename: 'some doc.pdf', path: 'attachments folder/some doc.pdf', targetPath: 'transcripts/some doc.pdf.md' },
			'transcript',
		)
		expect(result).toContain('[name](../attachments%20folder/some%20doc.pdf)')
	})

	it('always includes the auto-generated marker in output', () => {
		const result = applyTemplate('header', { filename: 'f', path: 'p', targetPath: 'p.md' }, 'transcript')
		expect(result).toContain(AUTOGENERATED_MARKER)
	})

	it('always includes the transcript in output', () => {
		const result = applyTemplate('header', { filename: 'f', path: 'p', targetPath: 'p.md' }, 'my transcript content')
		expect(result).toContain('my transcript content')
	})

	it('does not throw when template contains no tokens', () => {
		expect(() =>
			applyTemplate('just a plain header', { filename: 'f', path: 'p', targetPath: 'p.md' }, 'transcript'),
		).not.toThrow()
	})

	describe('canvas mode', () => {
		it('strips #height=500 from embed lines', () => {
			const result = applyTemplate(
				'![]({{path}}#height=500)',
				{ filename: 'f.canvas', path: 'f.canvas', targetPath: 'f.canvas.md' },
				'transcript',
				{ canvas: true },
			)
			expect(result).toContain('![](./f.canvas)')
			expect(result).not.toContain('#height=500')
		})

		it('strips any #height=N variant', () => {
			const result = applyTemplate(
				'![]({{path}}#height=1200)',
				{ filename: 'f.canvas', path: 'f.canvas', targetPath: 'f.canvas.md' },
				'transcript',
				{ canvas: true },
			)
			expect(result).not.toContain('#height=1200')
		})

		it('leaves embed lines without a height suffix unchanged', () => {
			const result = applyTemplate(
				'![]({{path}})',
				{ filename: 'f.canvas', path: 'f.canvas', targetPath: 'f.canvas.md' },
				'transcript',
				{ canvas: true },
			)
			expect(result).toContain('![](./f.canvas)')
		})
	})
})
