import { describe, expect, it } from 'vitest'
import { applyTemplate } from '../../src/utils/applyTemplate'
import { AUTOGENERATED_MARKER } from '../../src/utils/constants'

describe('applyTemplate', () => {
	it('replaces {{filename}} with the provided filename', () => {
		const result = applyTemplate(
			'File: {{filename}}',
			{ filename: 'test.pdf', path: 'docs/test.pdf' },
			'transcript',
		)
		expect(result).toContain('File: test.pdf')
		expect(result).not.toContain('{{filename}}')
	})

	it('replaces {{path}} with the provided path', () => {
		const result = applyTemplate(
			'![[{{path}}]]',
			{ filename: 'test.pdf', path: 'docs/test.pdf' },
			'transcript',
		)
		expect(result).toContain('![[docs/test.pdf]]')
		expect(result).not.toContain('{{path}}')
	})

	it('replaces {{path_encoded}} with spaces encoded as %20', () => {
		const result = applyTemplate(
			'[name]({{path_encoded}})\n![]({{path_encoded}}#height=500)',
			{ filename: 'my file.pdf', path: 'docs/my file.pdf' },
			'transcript',
		)
		expect(result).toContain('[name](docs/my%20file.pdf)')
		expect(result).toContain('![](docs/my%20file.pdf#height=500)')
		expect(result).not.toContain('{{path_encoded}}')
	})

	it('always includes the auto-generated marker in output', () => {
		const result = applyTemplate('header', { filename: 'f', path: 'p' }, 'transcript')
		expect(result).toContain(AUTOGENERATED_MARKER)
	})

	it('always includes the transcript in output', () => {
		const result = applyTemplate('header', { filename: 'f', path: 'p' }, 'my transcript content')
		expect(result).toContain('my transcript content')
	})

	it('does not throw when template contains no tokens', () => {
		expect(() =>
			applyTemplate('just a plain header', { filename: 'f', path: 'p' }, 'transcript'),
		).not.toThrow()
	})

	describe('canvas mode', () => {
		it('strips #height=500 from embed lines', () => {
			const result = applyTemplate(
				'![[{{path}}#height=500]]',
				{ filename: 'f.canvas', path: 'f.canvas' },
				'transcript',
				{ canvas: true },
			)
			expect(result).toContain('![[f.canvas]]')
			expect(result).not.toContain('#height=500')
		})

		it('strips any #height=N variant', () => {
			const result = applyTemplate(
				'![[{{path}}#height=1200]]',
				{ filename: 'f.canvas', path: 'f.canvas' },
				'transcript',
				{ canvas: true },
			)
			expect(result).not.toContain('#height=1200')
		})

		it('leaves embed lines without a height suffix unchanged', () => {
			const result = applyTemplate(
				'![[{{path}}]]',
				{ filename: 'f.canvas', path: 'f.canvas' },
				'transcript',
				{ canvas: true },
			)
			expect(result).toContain('![[f.canvas]]')
		})
	})
})
