import { mkdirSync, writeFileSync, utimesSync } from 'fs'
import { mkdtempSync } from 'fs'
import { tmpdir } from 'os'
import { join } from 'path'
import { describe, expect, it } from 'vitest'
import { runPlan } from '../../skills/ai-attachmate/scripts/plan'
import { AUTOGENERATED_MARKER } from '../../src/utils/constants'

function makeVault(settings?: Record<string, unknown>): string {
	const dir = mkdtempSync(join(tmpdir(), 'aam-vault-'))
	mkdirSync(join(dir, '.obsidian/plugins/ai-attachmate'), { recursive: true })
	if (settings) {
		writeFileSync(
			join(dir, '.obsidian/plugins/ai-attachmate/data.json'),
			JSON.stringify(settings),
		)
	}
	return dir
}

function touch(path: string, mtimeSec: number): void {
	utimesSync(path, mtimeSec, mtimeSec)
}

describe('runPlan', () => {
	it('classifies a brand-new PDF as newFiles', () => {
		const vault = makeVault()
		mkdirSync(join(vault, 'attachments'))
		writeFileSync(join(vault, 'attachments/foo.pdf'), 'pdf-bytes')

		const plan = runPlan(vault)
		expect(plan.newFiles).toEqual([
			{ source: 'attachments/foo.pdf', target: 'attachments/foo.pdf.md' },
		])
		expect(plan.staleFiles).toEqual([])
		expect(plan.orphans).toEqual([])
		expect(plan.upToDate).toBe(0)
	})

	it('classifies a transcript older than its source as stale and extracts userZone', () => {
		const vault = makeVault()
		mkdirSync(join(vault, 'attachments'))
		const src = join(vault, 'attachments/bar.png')
		const tgt = join(vault, 'attachments/bar.png.md')
		writeFileSync(src, 'png-bytes')
		writeFileSync(
			tgt,
			`# Notes\n\nI took notes here\n\n${AUTOGENERATED_MARKER}\n# Transcript\n\nold body\n`,
		)
		// Make target older than source
		touch(tgt, 1_000_000)
		touch(src, 2_000_000)

		const plan = runPlan(vault)
		expect(plan.newFiles).toEqual([])
		expect(plan.staleFiles).toHaveLength(1)
		expect(plan.staleFiles[0].source).toBe('attachments/bar.png')
		expect(plan.staleFiles[0].target).toBe('attachments/bar.png.md')
		expect(plan.staleFiles[0].userZone).toBe('# Notes\n\nI took notes here\n\n')
	})

	it('counts a transcript newer than its source as upToDate', () => {
		const vault = makeVault()
		mkdirSync(join(vault, 'attachments'))
		const src = join(vault, 'attachments/baz.pdf')
		const tgt = join(vault, 'attachments/baz.pdf.md')
		writeFileSync(src, 'pdf-bytes')
		writeFileSync(tgt, `header\n\n${AUTOGENERATED_MARKER}\n# Transcript\n\nbody\n`)
		touch(src, 1_000_000)
		touch(tgt, 2_000_000)

		const plan = runPlan(vault)
		expect(plan.upToDate).toBe(1)
		expect(plan.newFiles).toEqual([])
		expect(plan.staleFiles).toEqual([])
	})

	it('detects orphans: auto-generated transcript whose source is gone', () => {
		const vault = makeVault()
		mkdirSync(join(vault, 'attachments'))
		writeFileSync(
			join(vault, 'attachments/gone.pdf.md'),
			`header\n\n${AUTOGENERATED_MARKER}\n# Transcript\n\nbody\n`,
		)
		const plan = runPlan(vault)
		expect(plan.orphans).toEqual(['attachments/gone.pdf.md'])
	})

	it('does not treat user-written .md files as orphans', () => {
		const vault = makeVault()
		mkdirSync(join(vault, 'attachments'))
		// Looks like a target name but has no AUTOGENERATED_MARKER
		writeFileSync(join(vault, 'attachments/manual.pdf.md'), '# my own notes\n')
		const plan = runPlan(vault)
		expect(plan.orphans).toEqual([])
	})

	it('respects the configured fileFilter', () => {
		const vault = makeVault({ fileFilter: '**/attachments/*.pdf' })
		mkdirSync(join(vault, 'attachments'))
		mkdirSync(join(vault, 'other'))
		writeFileSync(join(vault, 'attachments/yes.pdf'), 'x')
		writeFileSync(join(vault, 'other/no.pdf'), 'x')

		const plan = runPlan(vault)
		expect(plan.newFiles.map((f) => f.source)).toEqual(['attachments/yes.pdf'])
	})

	it('honors a non-relative transcriptsFolder setting', () => {
		const vault = makeVault({ transcriptsFolder: 'transcripts' })
		mkdirSync(join(vault, 'attachments'))
		writeFileSync(join(vault, 'attachments/nested.pdf'), 'x')

		const plan = runPlan(vault)
		expect(plan.newFiles).toEqual([
			{ source: 'attachments/nested.pdf', target: 'transcripts/nested.pdf.md' },
		])
	})
})
