import { config } from 'dotenv'
import { beforeEach, describe, expect, it } from 'vitest'
import { FileDaoImpl } from '../../src/dao/FileDaoImpl'
import { GeminiAttachmentParserService } from '../../src/service/AttachmentParserService'
import { PngConverterService } from '../../src/service/PngConverterService'
import { AUTOGENERATED_MARKER } from '../../src/utils/constants'
import { InMemoryFileAdapter } from '../dao/InMemoryFileAdapter'
import { createTestImageFile } from '../utils/testFileUtils'

// Load environment variables from .env file
config()

describe('Integration Test: Image Conversion', () => {
	const TEST_TIMEOUT = 30000
	let fileAdapter: InMemoryFileAdapter
	let fileDao: FileDaoImpl
	let pngConverter: PngConverterService
	let createImageFile: (filename: string) => Promise<void>

	beforeEach((): void => {
		const apiKey = process.env.GOOGLE_API_KEY
		if (!apiKey) {
			throw new Error('GOOGLE_API_KEY environment variable is required for tests')
		}

		fileAdapter = new InMemoryFileAdapter()
		fileDao = new FileDaoImpl(fileAdapter)
		const imageParser = new GeminiAttachmentParserService(
			{ getApiKey: (): string => apiKey },
			'image/png',
			(): string =>
				'Parse text from the image. Return full text and also give me description of the image',
		)
		pngConverter = new PngConverterService(fileDao, 'transcripts', imageParser)

		// Clear dao to ensure a clean state
		fileAdapter.clear()

		// Create partially applied function with adapter instead of fileDao
		createImageFile = (filename: string): Promise<void> =>
			createTestImageFile(fileAdapter, filename)
	})

	function verifyMarkdownStructure(content: string, imageName: string): void {
		expect(content).toContain('# Notes')
		expect(content).toContain('# Content')
		expect(content).toContain(`File: [${imageName}](${imageName})`)
		expect(content).toContain(`![[${imageName}#height=500]]`)
		expect(content).toContain('> Please note: Deleting the original file will delete this file.')
		expect(content).toContain(AUTOGENERATED_MARKER)
		expect(content).toContain('# Transcript')
		expect(content.length).toBeGreaterThan(200)
	}

	it(
		'should create an image file, run the converter, and verify the .png.md file',
		async () => {
			// Step 1: Create a test image file using the FileAdapter
			await createImageFile('test-image.png')

			// Step 2: Run the converter
			await pngConverter.convertFiles()

			// Step 3: Verify that the .md file is created and contains expected structure
			const expectedMdPath = 'transcripts/test-image.png.md'
			const convertedContent = await fileAdapter.read(expectedMdPath)
			verifyMarkdownStructure(convertedContent, 'test-image.png')
		},
		{ timeout: TEST_TIMEOUT },
	)

	it(
		'should handle multiple image files',
		async () => {
			await createImageFile('test-image.png')
			await createImageFile('test-image2.png')
			await pngConverter.convertFiles()

			const files = [
				{ path: 'transcripts/test-image.png.md', name: 'test-image.png' },
				{ path: 'transcripts/test-image2.png.md', name: 'test-image2.png' },
			]

			for (const file of files) {
				const convertedContent = await fileAdapter.read(file.path)
				verifyMarkdownStructure(convertedContent, file.name)
			}
		},
		{ timeout: TEST_TIMEOUT },
	)

	it(
		'should update modified image files',
		async () => {
			await createImageFile('test-image.png')
			await pngConverter.convertFiles()

			await new Promise((resolve) => setTimeout(resolve, 3))
			await createImageFile('test-image2.png')
			await pngConverter.convertFiles()

			const expectedMdPath = 'transcripts/test-image2.png.md'
			const convertedContent = await fileAdapter.read(expectedMdPath)
			verifyMarkdownStructure(convertedContent, 'test-image2.png')
		},
		{ timeout: TEST_TIMEOUT },
	)

	it.skip(
		'should remove orphaned files',
		async () => {
			await createImageFile('test-image.png')
			await pngConverter.convertFiles()

			const mdPath = 'transcripts/test-image.png.md'
			expect(await fileAdapter.read(mdPath)).toBeDefined()

			await fileAdapter.delete('test-image.png')
			await pngConverter.convertFiles()

			await expect(fileAdapter.read(mdPath)).rejects.toThrow()
		},
		{ timeout: TEST_TIMEOUT },
	)
})
