import { beforeEach, describe, expect, it } from 'vitest';
import { PdfConverterService } from '../../src/service/PdfConverterService';
import { FileDaoImpl } from '../../src/dao/FileDaoImpl';
import { InMemoryFileAdapter } from '../dao/InMemoryFileAdapter';
import { AttachmentParserService } from '../../src/service/AttachmentParserService';
import { AUTOGENERATED_MARKER } from '../../src/utils/constants';
import { createTestImageFile, readTestFile } from '../utils/testFileUtils';

const MOCK_TRANSCRIPT = 'Mock transcript content';

const mockParser: AttachmentParserService = {
    validateApiKey: () => true,
    parseAttachmentContent: async () => MOCK_TRANSCRIPT,
};

describe('Integration Test: PDF Converter (fast, mock parser)', () => {
    let fileAdapter: InMemoryFileAdapter;
    let fileDao: FileDaoImpl;
    let pdfConverter: PdfConverterService;

    beforeEach(() => {
        fileAdapter = new InMemoryFileAdapter();
        fileDao = new FileDaoImpl(fileAdapter);
        pdfConverter = new PdfConverterService(fileDao, 'index', mockParser);
    });

    it('produces output exactly matching the fixture file', async () => {
        await createTestImageFile(fileAdapter, 'test.pdf', 'test.pdf');
        await pdfConverter.convertFiles();

        const actual = await fileAdapter.read('index/test.pdf.md');
        const expected = readTestFile('test.pdf.md');
        expect(actual).toEqual(expected);
    });

    it('uses full vault-relative path in embed and file link', async () => {
        await createTestImageFile(fileAdapter, 'sub folder/test.pdf', 'test.pdf');
        await pdfConverter.convertFiles();

        const content = await fileAdapter.read('index/test.pdf.md');
        expect(content).toContain('File: [test.pdf](sub folder/test.pdf)');
        expect(content).toContain('![[sub folder/test.pdf#height=500]]');
    });

    it('skips conversion when API key is not valid', async () => {
        const noKeyParser: AttachmentParserService = {
            validateApiKey: () => false,
            parseAttachmentContent: async () => 'should not be called',
        };
        const converter = new PdfConverterService(fileDao, 'index', noKeyParser);
        await createTestImageFile(fileAdapter, 'test.pdf', 'test.pdf');
        await converter.convertFiles();

        await expect(fileAdapter.read('index/test.pdf.md')).rejects.toThrow();
    });

    it('removes orphaned index file when source PDF is deleted', async () => {
        await createTestImageFile(fileAdapter, 'test.pdf', 'test.pdf');
        await fileDao.createOrUpdateFile('index/test.pdf.md', `${AUTOGENERATED_MARKER}\n# Transcript\n${MOCK_TRANSCRIPT}`);

        await fileAdapter.delete('test.pdf');
        await pdfConverter.convertFiles();

        await expect(fileAdapter.read('index/test.pdf.md')).rejects.toThrow();
    });

    it('does not modify index file when source PDF is unchanged', async () => {
        await createTestImageFile(fileAdapter, 'test.pdf', 'test.pdf');
        await new Promise(resolve => setTimeout(resolve, 3));
        await pdfConverter.convertFiles();

        await new Promise(resolve => setTimeout(resolve, 3));

        const mdPath = 'index/test.pdf.md';
        const timeBefore = (await fileAdapter.getFiles()).find(f => f.path === mdPath)?.modifiedTime;

        await new Promise(resolve => setTimeout(resolve, 3));
        await pdfConverter.convertFiles();

        const timeAfter = (await fileAdapter.getFiles()).find(f => f.path === mdPath)?.modifiedTime;
        expect(timeAfter).toBe(timeBefore);
    });
});
