import { beforeEach, describe, expect, it } from 'vitest'
import { FileDaoImpl } from '../../src/dao/FileDaoImpl'
import { CanvasService } from '../../src/service/CanvasService'
import { AUTOGENERATED_MARKER } from '../../src/utils/constants'
import { InMemoryFileAdapter } from '../dao/InMemoryFileAdapter'
import { readTestFile } from '../utils/testFileUtils'

const CANVAS_CONTENT = readTestFile('Test.canvas')

describe('FileDaoImpl deletion safety', () => {
	let fileAdapter: InMemoryFileAdapter
	let fileDao: FileDaoImpl

	beforeEach(() => {
		fileAdapter = new InMemoryFileAdapter()
		fileDao = new FileDaoImpl(fileAdapter)
	})

	it('deletes a file that contains the autogenerated marker', async () => {
		await fileDao.createOrUpdateFile(
			'transcripts/Test.canvas.md',
			`${AUTOGENERATED_MARKER}\n# Transcript\nsome content`,
		)
		await expect(fileDao.deleteFile('transcripts/Test.canvas.md')).resolves.toBeUndefined()
		await expect(fileAdapter.read('transcripts/Test.canvas.md')).rejects.toThrow()
	})

	it('refuses to delete a file that only contains old-format marker text', async () => {
		const oldContent =
			'This index file enables Obsidian and its plugins to manage canvas files effectively. It ensures alias files for canvases appear in graphs and allows plugins compatible only with MD files to access these files.'
		await fileDao.createOrUpdateFile('transcripts/OldFormat.canvas.md', oldContent)
		await expect(fileDao.deleteFile('transcripts/OldFormat.canvas.md')).rejects.toThrow()
	})
})

describe('Integration Test: Orphan Detection', () => {
	let fileAdapter: InMemoryFileAdapter
	let fileDao: FileDaoImpl

	beforeEach(() => {
		fileAdapter = new InMemoryFileAdapter()
		fileDao = new FileDaoImpl(fileAdapter)
	})

	it('vault-root-relative — orphan in transcripts/ is cleaned up (no regression)', async () => {
		await fileDao.createOrUpdateFile('Test.canvas', CANVAS_CONTENT)
		await fileDao.createOrUpdateFile(
			'transcripts/Test.canvas.md',
			`${AUTOGENERATED_MARKER}\n# Transcript\ncontent`,
		)

		const service = new CanvasService(fileDao, {
			canvasPostfix: '.canvas.md',
			runOnStart: false,
			transcriptsFolder: 'transcripts',
		})

		await fileAdapter.delete('Test.canvas')
		await service.convertFiles()

		await expect(fileAdapter.read('transcripts/Test.canvas.md')).rejects.toThrow()
	})

	it('../ — deleting the source removes the orphaned index file at vault root', async () => {
		await fileDao.createOrUpdateFile('attachments/Test.canvas', CANVAS_CONTENT)
		await fileDao.createOrUpdateFile(
			'Test.canvas.md',
			`${AUTOGENERATED_MARKER}\n# Transcript\ncontent`,
		)

		const service = new CanvasService(fileDao, {
			canvasPostfix: '.canvas.md',
			runOnStart: false,
			transcriptsFolder: '../',
		})

		await fileAdapter.delete('attachments/Test.canvas')
		await service.convertFiles()

		await expect(fileAdapter.read('Test.canvas.md')).rejects.toThrow()
	})

	it('../ — two sources, one deleted → orphan removed, sibling transcript kept', async () => {
		await fileDao.createOrUpdateFile('attachments/A.canvas', CANVAS_CONTENT)
		await fileDao.createOrUpdateFile('attachments/B.canvas', CANVAS_CONTENT)
		await fileDao.createOrUpdateFile(
			'A.canvas.md',
			`${AUTOGENERATED_MARKER}\n# Transcript\ncontent`,
		)
		await fileDao.createOrUpdateFile(
			'B.canvas.md',
			`${AUTOGENERATED_MARKER}\n# Transcript\ncontent`,
		)

		const service = new CanvasService(fileDao, {
			canvasPostfix: '.canvas.md',
			runOnStart: false,
			transcriptsFolder: '../',
		})

		await fileAdapter.delete('attachments/B.canvas')
		await service.convertFiles()

		// B orphan removed, A kept
		await expect(fileAdapter.read('B.canvas.md')).rejects.toThrow()
		expect(await fileAdapter.read('A.canvas.md')).toBeDefined()
	})

	it('./index — deleting the source removes the orphan in the relative subfolder', async () => {
		await fileDao.createOrUpdateFile('attachments/Test.canvas', CANVAS_CONTENT)
		await fileDao.createOrUpdateFile(
			'attachments/index/Test.canvas.md',
			`${AUTOGENERATED_MARKER}\n# Transcript\ncontent`,
		)

		const service = new CanvasService(fileDao, {
			canvasPostfix: '.canvas.md',
			runOnStart: false,
			transcriptsFolder: './index',
		})

		await fileAdapter.delete('attachments/Test.canvas')
		await service.convertFiles()

		await expect(fileAdapter.read('attachments/index/Test.canvas.md')).rejects.toThrow()
	})

	it('content-marker safety — user file with .canvas.md extension in output dir is not deleted', async () => {
		await fileDao.createOrUpdateFile('attachments/Test.canvas', CANVAS_CONTENT)
		await fileDao.createOrUpdateFile(
			'Test.canvas.md',
			`${AUTOGENERATED_MARKER}\n# Transcript\ncontent`,
		)

		const service = new CanvasService(fileDao, {
			canvasPostfix: '.canvas.md',
			runOnStart: false,
			transcriptsFolder: '../',
		})

		// User creates their own .canvas.md note at root (no content marker)
		await fileDao.createOrUpdateFile('MyNote.canvas.md', '# My own note, no marker here')

		await fileAdapter.delete('attachments/Test.canvas')
		await service.convertFiles()

		// Plugin-generated orphan deleted, user file untouched
		await expect(fileAdapter.read('Test.canvas.md')).rejects.toThrow()
		expect(await fileAdapter.read('MyNote.canvas.md')).toBe('# My own note, no marker here')
	})
})
